sudo: false

language: php

php:
    - 5.5
    - 5.6
    - 7.0
    - 7.1
    - hhvm

before_script:
    - travis_retry composer self-update
    - if [[ $TRAVIS_PHP_VERSION == "5.5" ]]; then composer remove --dev phpbench/phpbench; fi
    - if [[ $TRAVIS_PHP_VERSION == "hhvm" ]]; then composer remove --dev phpbench/phpbench; fi
    - travis_retry composer install --no-interaction

script:
    - vendor/bin/phpcs --standard=psr2 ./src
    - vendor/bin/phpunit --coverage-text --bootstrap vendor/autoload.php --coverage-clover=coverage.xml tests/

after_success:
    - if [[ $TRAVIS_PHP_VERSION != "hhvm" ]]; then bash <(curl -s https://codecov.io/bash); fi

cache:
    directories:
        - $HOME/.composer/cache
